apiVersion: batch/v1
kind: Job
metadata:
  name: project-a
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: hello-world
      restartPolicy: Never
  backoffLimit: 0
